engines:
  stylelint:
    enabled: true
  eslint:
    enabled: true
checks:
  method-lines:
    config:
      threshold: 35
ratings:
  paths:
    - "**.css"
    - "**.js"
exclude_paths:
- "node_modules"
- "test"
- ".githooks"
- "assets/js"
- "assets/css"
