engines:
  stylelint:
    enabled: true
  eslint:
    enabled: true
checks:
  method-lines:
    config:
      threshold: 30
exclude_paths:
- "node_modules"
- "test"
- ".githooks"
- "assets/js"
- "assets/css"
