sudo: false
language: node_js

git:
  depth: 1

branches:
  only:
    - master
    - /^greenkeeper/.*$/

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run lint
  - npm run test
